apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-master
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    name: locust
    role: master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        name: {{ template "fullname" . }}-master
        role: master
      
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "fix-perms",
            "image": "busybox",
            "imagePullPolicy": "{{ .Values.image.pullPolicy }}",
            "command": [
              "sh",
              "-c",
              "/bin/chmod 400 /etc/git-secret/ssh"
            ],
            "volumeMounts": [
              {
                "name": "git-secret",
                "mountPath": "/etc/git-secret/ssh",
                "subPath": "ssh"
              }
            ],
            "securityContext": {
              "runAsUser": 0
            }
          },
          {
            "name": "tasks",
            "image": "{{.Values.image.gitSync}}",
            "imagePullPolicy": "{{.Values.image.pullPolicy}}",
            "args": [
              "--repo",
              "{{ .Values.task.repo }}",
              "--dest",
              "{{ .Values.task.dest }}",
              "--branch",
              "{{ .Values.task.branch }}",
              "--ssh",
              "--one-time"
            ],
            "volumeMounts": [
              {
                "mountPath": "/git/",
                "name": "git-volume"
              },
              {
                "name": "git-secret",
                "mountPath": "/etc/git-secret/ssh",
                "subPath": "ssh"
              }
            ],
            "securityContext": {
              "runAsUser": 0
            }
          }
        ]'
    spec:
      volumes:
      - name: git-secret
        secret:
          secretName: {{ .Values.sshSecret }}
          defaultMode: 0400
      - name: git-volume
        emptyDir: {}

      # initContainers:
      # # Fix the ssh secrets permissions
      # - name: fix-perms
      #   image: busybox
      #   command:
      #   - sh
      #   - -c
      #   - /bin/chmod 400 /etc/git-secret/ssh
      #   volumeMounts:
      #   - name: git-secret
      #     mountPath: /etc/git-secret/ssh
      #     subPath: ssh
      #   securityContext:
      #     runAsUser: 0
      #
      # # Go get the tasks from git
      # - name: tasks
      #   image: {{ .Values.image.gitSync }}
      #   imagePullPolicy: {{ .Values.image.pullPolicy }}
      #   args: [
      #     "--repo", "{{ .Values.task.repo }}",
      #     "--dest", "{{ .Values.task.dest }}",
      #     "--branch", "{{ .Values.task.branch }}",
      #     "--ssh",
      #     "--one-time"
      #   ]
      #   volumeMounts:
      #   - mountPath: /git/
      #     name: git-volume
      #   - name: git-secret
      #     mountPath: /etc/git-secret/ssh
      #     subPath: ssh
      #   securityContext:
      #     runAsUser: 0

      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - /bin/sh
          - -c
          - "/bin/ls -lR /{{ .Values.task.dest }}/{{ .Values.task.taskDir }}/. && /usr/local/bin/locust.sh"
        workingDir: /{{ .Values.task.dest }}/{{ .Values.task.taskDir }}
        volumeMounts:
        # Mount the git repo for the system under test
        - mountPath: /{{ .Values.task.dest }}/{{ .Values.task.taskDir }}
          name: git-volume
          subPath: {{ .Values.task.dest }}/{{ .Values.task.taskDir }}
        ports:
        - name: loc-master-web
          containerPort: 8089
          protocol: TCP
        - name: loc-master-p1
          containerPort: 5557
          protocol: TCP
        - name: loc-master-p2
          containerPort: 5558
          protocol: TCP
        env:
        - name: LOCUST_MODE
          value: master
        - name: LOCUST_MASTER
          value: {{ template "fullname" . }}
        - name: TARGET_HOST
          value: {{ .Values.task.targetHost }}
        - name: LOCUST_TASKS
          value: /{{ .Values.task.dest }}/{{ .Values.task.taskDir }}/{{ .Values.task.tasks }}
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: {{ .Values.service.internalPort }}
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
