apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-worker
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    name: locust
    role: worker
spec:
  replicas: {{ .Values.workerCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        name: locust
        role: worker
    spec:
      volumes:
      - name: git-secret
        secret:
          secretName: {{ .Values.sshSecret }}
          defaultMode: 0400
      - name: git-volume
        emptyDir: {}

      initContainers:
      # Fix permissions for ssh secret
      - name: fix-perms
        image: busybox
        command:
        - sh
        - -c
        - /bin/chmod 400 /etc/git-secret/ssh
        volumeMounts:
        - name: git-secret
          mountPath: /etc/git-secret/ssh
          subPath: ssh
        securityContext:
          runAsUser: 0

      # Go get the tasks from git
      - name: tasks
        image: {{ .Values.image.gitSync }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: [
          "--repo", "{{ .Values.task.repo }}", 
          "--dest", "{{ .Values.task.dest }}",
          "--branch", "{{ .Values.task.branch }}",
          "--ssh",
          "--one-time"
        ]
        volumeMounts:
        - mountPath: /git/
          name: git-volume
        - name: git-secret
          mountPath: /etc/git-secret/ssh
          subPath: ssh
        securityContext:
          runAsUser: 0

      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        workingDir: /{{ .Values.task.dest }}/{{ .Values.task.taskDir }}
        volumeMounts:
        # Mount the git repo for the system under test
        - mountPath: /{{ .Values.task.dest }}/{{ .Values.task.taskDir }}
          name: git-volume
          subPath: {{ .Values.task.dest }}/{{ .Values.task.taskDir }}
        env:
        - name: LOCUST_MODE
          value: worker
        - name: LOCUST_MASTER
          value: {{ template "fullname" . }}
        - name: TARGET_HOST
          value: {{ .Values.task.targetHost }}
        - name: LOCUST_TASKS
          value: /{{ .Values.task.dest }}/{{ .Values.task.taskDir }}/{{ .Values.task.tasks }}
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: {{ .Values.service.internalPort }}
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
